// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: GuidAttribute("c52f5919-ce5d-456d-b81d-838da19a89bc")]
[assembly: AssemblyTitleAttribute("AutofacContrib.NSubstitute")]
[assembly: AssemblyProductAttribute("AutofacContrib.NSubstitute")]
[assembly: AssemblyCopyrightAttribute("Copyright �  2012")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("3.3.3.0")]
[assembly: AssemblyFileVersionAttribute("3.3.3.0")]
[assembly: AssemblyInformationalVersionAttribute("{\"buildVersion\":\"3.3.3-ci1406200436\",\"buildDate\":\"2014-06-20T04:36:36Z\",\"gitCommit\":\"639a3b86f2e0c1441cc4ec05ae3ec9737cd75141\"}")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.3.3.0";
    }
}
